2018-05-04 10:16:37,861 [5] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@UY_Number nvarchar(36),@Number nvarchar(4000))SELECT top 1 Num' 需要参数 '@Number'，但未提供该参数。
2018-05-04 10:17:34,811 [5] ERROR LeaRun.DataAccess.DbHelper - 另一个 SqlParameterCollection 中已包含 SqlParameter。
2018-05-04 11:13:57,254 [97] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@UY_Number nvarchar(36),@Number nvarchar(4000))SELECT top 1 Num' 需要参数 '@Number'，但未提供该参数。
2018-05-04 11:14:19,001 [101] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@UY_Number nvarchar(36),@Number nvarchar(4000))SELECT top 1 Num' 需要参数 '@Number'，但未提供该参数。
2018-05-04 12:28:35,522 [114] ERROR LeaRun.DataAccess.DbHelper - 不能将值 NULL 插入列 'Classify'，表 'AmmeterDB.dbo.Am_AmmeterMoney'；列不允许有 Null 值。INSERT 失败。
语句已终止。
2018-05-04 12:28:40,066 [112] ERROR LeaRun.DataAccess.DbHelper - 不能将值 NULL 插入列 'Classify'，表 'AmmeterDB.dbo.Am_AmmeterMoney'；列不允许有 Null 值。INSERT 失败。
语句已终止。
2018-05-04 12:29:08,760 [114] ERROR LeaRun.DataAccess.DbHelper - 不能将值 NULL 插入列 'Classify'，表 'AmmeterDB.dbo.Am_AmmeterMoney'；列不允许有 Null 值。INSERT 失败。
语句已终止。
2018-05-04 14:40:36,370 [112] ERROR LeaRun.DataAccess.DbHelper - 不能将值 NULL 插入列 'Classify'，表 'AmmeterDB.dbo.Am_AmmeterMoney'；列不允许有 Null 值。INSERT 失败。
语句已终止。
2018-05-04 14:40:57,992 [109] ERROR LeaRun.DataAccess.DbHelper - 不能将值 NULL 插入列 'Classify'，表 'AmmeterDB.dbo.Am_AmmeterMoney'；列不允许有 Null 值。INSERT 失败。
语句已终止。
2018-05-04 14:41:02,489 [113] ERROR LeaRun.DataAccess.DbHelper - 不能将值 NULL 插入列 'Classify'，表 'AmmeterDB.dbo.Am_AmmeterMoney'；列不允许有 Null 值。INSERT 失败。
语句已终止。
2018-05-04 14:41:19,643 [109] ERROR LeaRun.DataAccess.DbHelper - 不能将值 NULL 插入列 'Classify'，表 'AmmeterDB.dbo.Am_AmmeterMoney'；列不允许有 Null 值。INSERT 失败。
语句已终止。
2018-05-04 14:41:40,312 [109] ERROR LeaRun.DataAccess.DbHelper - 另一个 SqlParameterCollection 中已包含 SqlParameter。
2018-05-04 14:42:24,066 [109] ERROR LeaRun.DataAccess.DbHelper - 不能将值 NULL 插入列 'Classify'，表 'AmmeterDB.dbo.Am_AmmeterMoney'；列不允许有 Null 值。INSERT 失败。
语句已终止。
2018-05-04 15:08:35,882 [29] ERROR LeaRun.DataAccess.DbHelper - 列名 'AmmeterMoneyNumber' 无效。
2018-05-04 15:09:22,426 [34] ERROR LeaRun.DataAccess.DbHelper - 列名 'AmmeterMoneyNumber' 无效。
2018-05-04 15:09:32,700 [36] ERROR LeaRun.DataAccess.DbHelper - 列名 'AmmeterMoneyNumber' 无效。
2018-05-04 15:10:03,903 [36] ERROR LeaRun.DataAccess.DbHelper - 列名 'AmmeterMoneyNumber' 无效。
2018-05-04 17:26:24,958 [69] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@U_Number nvarchar(36),@Number nvarchar(4000))SELECT top 1 Numb' 需要参数 '@Number'，但未提供该参数。
2018-05-04 17:27:08,428 [69] ERROR LeaRun.DataAccess.DbHelper - 另一个 SqlParameterCollection 中已包含 SqlParameter。
2018-05-04 17:27:30,207 [74] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@U_Number nvarchar(36),@Number nvarchar(4000))SELECT top 1 Numb' 需要参数 '@Number'，但未提供该参数。
2018-05-04 17:32:37,234 [17] ERROR LeaRun.DataAccess.DbHelper - “Repair_Number”附近有语法错误。
2018-05-04 17:33:29,626 [17] ERROR LeaRun.DataAccess.DbHelper - 另一个 SqlParameterCollection 中已包含 SqlParameter。
2018-05-04 17:34:08,078 [20] ERROR LeaRun.DataAccess.DbHelper - “Repair_Number”附近有语法错误。
