2018-04-14 18:15:01,141 [99] ERROR LeaRun.DataAccess.DbHelper - 不能将值 NULL 插入列 'Number'，表 'AmmeterDB.dbo.Ho_PartnerUser'；列不允许有 Null 值。INSERT 失败。
语句已终止。
2018-04-14 18:16:29,123 [99] ERROR LeaRun.DataAccess.DbHelper - 不能将值 NULL 插入列 'Birthday'，表 'AmmeterDB.dbo.Ho_PartnerUser'；列不允许有 Null 值。INSERT 失败。
语句已终止。
2018-04-14 18:20:58,607 [99] ERROR LeaRun.DataAccess.DbHelper - 不能将值 NULL 插入列 'Birthday'，表 'AmmeterDB.dbo.Ho_PartnerUser'；列不允许有 Null 值。INSERT 失败。
语句已终止。
