2018-05-19 13:32:36,913 [14] ERROR LeaRun.DataAccess.DbHelper - UPDATE 语句与 FOREIGN KEY 约束"FK_Am_Ammeter_Am_AmmeterMoney"冲突。该冲突发生于数据库"AmmeterDB"，表"dbo.Am_AmmeterMoney", column 'Number'。
语句已终止。
2018-05-19 13:33:14,947 [14] ERROR LeaRun.DataAccess.DbHelper - UPDATE 语句与 FOREIGN KEY 约束"FK_Am_Ammeter_Am_AmmeterMoney"冲突。该冲突发生于数据库"AmmeterDB"，表"dbo.Am_AmmeterMoney", column 'Number'。
语句已终止。
2018-05-19 13:39:19,893 [29] ERROR LeaRun.DataAccess.DbHelper - UPDATE 语句与 FOREIGN KEY 约束"FK_Am_Ammeter_Am_AmmeterMoney"冲突。该冲突发生于数据库"AmmeterDB"，表"dbo.Am_AmmeterMoney", column 'Number'。
语句已终止。
2018-05-19 13:39:46,102 [46] ERROR LeaRun.DataAccess.DbHelper - UPDATE 语句与 FOREIGN KEY 约束"FK_Am_Ammeter_Am_AmmeterMoney"冲突。该冲突发生于数据库"AmmeterDB"，表"dbo.Am_AmmeterMoney", column 'Number'。
语句已终止。
2018-05-19 13:44:47,256 [46] ERROR LeaRun.DataAccess.DbHelper - UPDATE 语句与 FOREIGN KEY 约束"FK_Am_Ammeter_Am_AmmeterMoney"冲突。该冲突发生于数据库"AmmeterDB"，表"dbo.Am_AmmeterMoney", column 'Number'。
语句已终止。
