2018-05-15 15:27:58,594 [13] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@UY_Number nvarchar(36),@Number nvarchar(4000))SELECT top 1 Num' 需要参数 '@Number'，但未提供该参数。
2018-05-15 19:22:41,560 [93] ERROR LeaRun.DataAccess.DbHelper - 不能将值 NULL 插入列 'OverTime'，表 'AmmeterDB.dbo.Am_Task'；列不允许有 Null 值。INSERT 失败。
语句已终止。
2018-05-15 19:22:41,613 [93] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@AM_Code"。
2018-05-15 19:23:20,409 [93] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@AM_Code"。
2018-05-15 19:23:50,717 [75] ERROR LeaRun.DataAccess.DbHelper - 不能将值 NULL 插入列 'OverTime'，表 'AmmeterDB.dbo.Am_Task'；列不允许有 Null 值。INSERT 失败。
语句已终止。
2018-05-15 19:25:45,409 [8] ERROR LeaRun.DataAccess.DbHelper - 不能将值 NULL 插入列 'OverTime'，表 'AmmeterDB.dbo.Am_Task'；列不允许有 Null 值。INSERT 失败。
语句已终止。
2018-05-15 19:25:54,329 [15] ERROR LeaRun.DataAccess.DbHelper - 不能将值 NULL 插入列 'OverTime'，表 'AmmeterDB.dbo.Am_Task'；列不允许有 Null 值。INSERT 失败。
语句已终止。
2018-05-15 19:28:56,884 [7] ERROR LeaRun.DataAccess.DbHelper - 不能将值 NULL 插入列 'OverTime'，表 'AmmeterDB.dbo.Am_Task'；列不允许有 Null 值。INSERT 失败。
语句已终止。
