2018-04-25 12:23:42,320 [50] ERROR LeaRun.DataAccess.DbHelper - “b”附近有语法错误。
2018-04-25 16:19:25,238 [5] ERROR LeaRun.DataAccess.DbHelper - “b”附近有语法错误。
2018-04-25 16:22:34,307 [13] ERROR LeaRun.DataAccess.DbHelper - 不能将值 NULL 插入列 'Moeny'，表 'AmmeterDB.dbo.Am_Charge'；列不允许有 Null 值。INSERT 失败。
语句已终止。
2018-04-25 16:23:23,937 [17] ERROR LeaRun.DataAccess.DbHelper - 不能将值 NULL 插入列 'Moeny'，表 'AmmeterDB.dbo.Am_Charge'；列不允许有 Null 值。INSERT 失败。
语句已终止。
