2018-05-08 10:51:57,006 [21] ERROR LeaRun.DataAccess.DbHelper - 不能将值 NULL 插入列 'Number'，表 'AmmeterDB.dbo.Am_RepairAnswer'；列不允许有 Null 值。INSERT 失败。
语句已终止。
2018-05-08 10:51:57,035 [21] ERROR LeaRun.DataAccess.DbHelper - 无法更新标识列 'RepairCode'。
2018-05-08 10:54:28,632 [37] ERROR LeaRun.DataAccess.DbHelper - 不能将值 NULL 插入列 'Number'，表 'AmmeterDB.dbo.Am_RepairAnswer'；列不允许有 Null 值。INSERT 失败。
语句已终止。
2018-05-08 10:54:45,629 [37] ERROR LeaRun.DataAccess.DbHelper - 无法更新标识列 'RepairCode'。
2018-05-08 10:56:47,532 [37] ERROR LeaRun.DataAccess.DbHelper - 不能将值 NULL 插入列 'Number'，表 'AmmeterDB.dbo.Am_RepairAnswer'；列不允许有 Null 值。INSERT 失败。
语句已终止。
2018-05-08 10:56:47,552 [37] ERROR LeaRun.DataAccess.DbHelper - 无法更新标识列 'RepairCode'。
2018-05-08 10:58:33,614 [11] ERROR LeaRun.DataAccess.DbHelper - 无法更新标识列 'RepairCode'。
2018-05-08 10:59:19,346 [11] ERROR LeaRun.DataAccess.DbHelper - 无法更新标识列 'RepairCode'。
