2018-05-05 10:17:10,124 [19] ERROR LeaRun.DataAccess.DbHelper - “CollectorCode”附近有语法错误。
2018-05-05 10:25:22,209 [35] ERROR LeaRun.DataAccess.DbHelper - 列名 'CollectorNumber' 无效。
2018-05-05 10:42:41,917 [7] ERROR LeaRun.DataAccess.DbHelper - 列名 'CollectorNumber' 无效。
2018-05-05 10:43:12,269 [42] ERROR LeaRun.DataAccess.DbHelper - 列名 'CollectorNumber' 无效。
2018-05-05 10:43:58,941 [42] ERROR LeaRun.DataAccess.DbHelper - 另一个 SqlParameterCollection 中已包含 SqlParameter。
2018-05-05 10:44:22,902 [7] ERROR LeaRun.DataAccess.DbHelper - 列名 'CollectorNumber' 无效。
2018-05-05 10:45:16,404 [16] ERROR LeaRun.DataAccess.DbHelper - 列名 'CollectorNumber' 无效。
2018-05-05 15:06:17,103 [170] ERROR LeaRun.DataAccess.DbHelper - 不能将值 NULL 插入列 'UserTime'，表 'AmmeterDB.dbo.Am_Ammeter'；列不允许有 Null 值。INSERT 失败。
语句已终止。
2018-05-05 15:06:45,215 [173] ERROR LeaRun.DataAccess.DbHelper - 不能将值 NULL 插入列 'UserTime'，表 'AmmeterDB.dbo.Am_Ammeter'；列不允许有 Null 值。INSERT 失败。
语句已终止。
2018-05-05 15:07:05,324 [173] ERROR LeaRun.DataAccess.DbHelper - 不能将值 NULL 插入列 'SencondAlarm'，表 'AmmeterDB.dbo.Am_Ammeter'；列不允许有 Null 值。INSERT 失败。
语句已终止。
2018-05-05 15:56:51,759 [5] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@Number nvarchar(4000))SELECT top 1 Number,Name,Classify,First,' 需要参数 '@Number'，但未提供该参数。
2018-05-05 16:01:11,392 [15] ERROR LeaRun.DataAccess.DbHelper - 不能将值 NULL 插入列 'Number'，表 'AmmeterDB.dbo.Am_Ammeter'；列不允许有 Null 值。INSERT 失败。
语句已终止。
2018-05-05 16:01:24,129 [15] ERROR LeaRun.DataAccess.DbHelper - 不能将值 NULL 插入列 'Number'，表 'AmmeterDB.dbo.Am_Ammeter'；列不允许有 Null 值。INSERT 失败。
语句已终止。
2018-05-05 16:02:04,029 [27] ERROR LeaRun.DataAccess.DbHelper - 不能将值 NULL 插入列 'Number'，表 'AmmeterDB.dbo.Am_Ammeter'；列不允许有 Null 值。INSERT 失败。
语句已终止。
2018-05-05 18:32:07,891 [51] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@UY_Number nvarchar(36),@U_Name nvarchar(4000))Select Count(1) ' 需要参数 '@U_Name'，但未提供该参数。
2018-05-05 20:03:57,519 [30] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@UY_Number nvarchar(36),@Number nvarchar(4000))SELECT top 1 Num' 需要参数 '@Number'，但未提供该参数。
2018-05-05 20:04:13,931 [23] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@UY_Number nvarchar(36),@Number nvarchar(4000))SELECT top 1 Num' 需要参数 '@Number'，但未提供该参数。
2018-05-05 20:05:57,465 [18] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@UY_Number nvarchar(36),@Number nvarchar(4000))SELECT top 1 Num' 需要参数 '@Number'，但未提供该参数。
2018-05-05 15:01:55,471 [128] ERROR LeaRun.DataAccess.DbHelper - 关键字 'and' 附近有语法错误。
2018-05-05 15:03:36,536 [129] ERROR LeaRun.DataAccess.DbHelper - 关键字 'and' 附近有语法错误。
2018-05-05 15:05:19,473 [129] ERROR LeaRun.DataAccess.DbHelper - 关键字 'and' 附近有语法错误。
2018-05-05 15:06:02,773 [164] ERROR LeaRun.DataAccess.DbHelper - 关键字 'and' 附近有语法错误。
2018-05-05 15:25:46,226 [136] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@UserNumber nvarchar(4000))Select Count(1) From (SELECT  *
   ' 需要参数 '@UserNumber'，但未提供该参数。
