2018-05-08 16:58:55,469 [252] ERROR LeaRun.DataAccess.DbHelper - 列名 'Ammeter_Number' 无效。
2018-05-08 17:00:09,663 [244] ERROR LeaRun.DataAccess.DbHelper - 列名 'Ammeter_Number' 无效。
2018-05-08 17:01:26,126 [242] ERROR LeaRun.DataAccess.DbHelper - 列名 'UY_Number' 无效。
2018-05-08 17:02:28,885 [242] ERROR LeaRun.DataAccess.DbHelper - 另一个 SqlParameterCollection 中已包含 SqlParameter。
2018-05-08 17:06:47,274 [238] ERROR LeaRun.DataAccess.DbHelper - 列名 'UY_Number' 无效。
2018-05-08 17:07:05,128 [241] ERROR LeaRun.DataAccess.DbHelper - 列名 'UY_Number' 无效。
