2018-04-19 11:55:44,505 [199] ERROR LeaRun.DataAccess.DbHelper - 列名 'CollectorCode' 无效。
2018-04-19 12:24:35,532 [189] ERROR LeaRun.DataAccess.DbHelper - 列名 'CollectorCode' 无效。
2018-04-19 12:26:36,815 [186] ERROR LeaRun.DataAccess.DbHelper - 列名 'CollectorCode' 无效。
2018-04-19 12:27:27,259 [37] ERROR LeaRun.DataAccess.DbHelper - 列名 'CollectorCode' 无效。
2018-04-19 12:28:09,005 [233] ERROR LeaRun.DataAccess.DbHelper - 列名 'CollectorCode' 无效。
