2018-05-09 10:34:02,951 [38] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@UY_Number"。
2018-05-09 10:34:58,850 [38] ERROR LeaRun.DataAccess.DbHelper - 列名 'Template_Number' 无效。
2018-05-09 10:43:06,789 [35] ERROR LeaRun.DataAccess.DbHelper - 不能将值 NULL 插入列 'ChargeItem_ChargeType'，表 'AmmeterDB.dbo.Am_TemplateContent'；列不允许有 Null 值。INSERT 失败。
语句已终止。
2018-05-09 10:45:41,591 [34] ERROR LeaRun.DataAccess.DbHelper - 不能将值 NULL 插入列 'ChargeItem_ChargeType'，表 'AmmeterDB.dbo.Am_TemplateContent'；列不允许有 Null 值。INSERT 失败。
语句已终止。
2018-05-09 10:48:56,838 [29] ERROR LeaRun.DataAccess.DbHelper - 不能将值 NULL 插入列 'ChargeItem_ChargeType'，表 'AmmeterDB.dbo.Am_TemplateContent'；列不允许有 Null 值。INSERT 失败。
语句已终止。
2018-05-09 10:53:04,668 [9] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@UY_Number"。
2018-05-09 10:53:16,020 [23] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@UY_Number"。
2018-05-09 11:43:39,099 [61] ERROR LeaRun.DataAccess.DbHelper - 列名 'Accout' 无效。
2018-05-09 11:44:30,023 [61] ERROR LeaRun.DataAccess.DbHelper - 另一个 SqlParameterCollection 中已包含 SqlParameter。
2018-05-09 11:44:50,401 [64] ERROR LeaRun.DataAccess.DbHelper - 列名 'Accout' 无效。
2018-05-09 11:46:35,484 [64] ERROR LeaRun.DataAccess.DbHelper - 另一个 SqlParameterCollection 中已包含 SqlParameter。
2018-05-09 14:41:46,341 [9] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@Account"。
2018-05-09 15:09:42,560 [13] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@Account"。
2018-05-09 18:27:26,502 [15] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@UY_Number nvarchar(36),@AmmeterNumber nvarchar(4000))Select Co' 需要参数 '@AmmeterNumber'，但未提供该参数。
2018-05-09 18:28:24,842 [83] ERROR LeaRun.DataAccess.DbHelper - 列名 'UY_Number' 无效。
2018-05-09 18:53:30,067 [19] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@F_U_Number nvarchar(36),@AmmeterNumber nvarchar(4000))Select C' 需要参数 '@AmmeterNumber'，但未提供该参数。
2018-05-09 18:54:18,743 [19] ERROR LeaRun.DataAccess.DbHelper - 另一个 SqlParameterCollection 中已包含 SqlParameter。
2018-05-09 18:54:23,640 [19] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@F_U_Number nvarchar(36),@AmmeterNumber nvarchar(4000))Select C' 需要参数 '@AmmeterNumber'，但未提供该参数。
2018-05-09 18:54:27,656 [13] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@F_U_Number nvarchar(36),@AmmeterNumber nvarchar(4000))Select C' 需要参数 '@AmmeterNumber'，但未提供该参数。
2018-05-09 18:54:51,054 [18] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@F_U_Number nvarchar(36),@AmmeterNumber nvarchar(4000))Select C' 需要参数 '@AmmeterNumber'，但未提供该参数。
