2018-05-05 15:01:55,471 [128] ERROR LeaRun.DataAccess.DbHelper - 关键字 'and' 附近有语法错误。
2018-05-05 15:03:36,536 [129] ERROR LeaRun.DataAccess.DbHelper - 关键字 'and' 附近有语法错误。
2018-05-05 15:05:19,473 [129] ERROR LeaRun.DataAccess.DbHelper - 关键字 'and' 附近有语法错误。
2018-05-05 15:06:02,773 [164] ERROR LeaRun.DataAccess.DbHelper - 关键字 'and' 附近有语法错误。
2018-05-05 15:25:46,226 [136] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@UserNumber nvarchar(4000))Select Count(1) From (SELECT  *
   ' 需要参数 '@UserNumber'，但未提供该参数。
