2018-04-26 18:06:42,716 [86] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@U_Number nvarchar(36),@Number nvarchar(4000))SELECT top 1 Numb' 需要参数 '@Number'，但未提供该参数。
2018-04-26 19:23:51,459 [8] ERROR LeaRun.DataAccess.DbHelper - “U_Number”附近有语法错误。
2018-04-26 19:24:13,402 [8] ERROR LeaRun.DataAccess.DbHelper - 另一个 SqlParameterCollection 中已包含 SqlParameter。
2018-04-26 20:23:24,050 [111] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@U_Number nvarchar(36),@Number nvarchar(4000))SELECT top 1 Numb' 需要参数 '@Number'，但未提供该参数。
2018-04-26 20:24:06,947 [121] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@U_Number nvarchar(36),@Number nvarchar(4000))SELECT top 1 Numb' 需要参数 '@Number'，但未提供该参数。
2018-04-26 20:25:21,234 [122] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@U_Number nvarchar(36),@Number nvarchar(4000))SELECT top 1 Numb' 需要参数 '@Number'，但未提供该参数。
2018-04-26 20:25:29,832 [113] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@U_Number nvarchar(36),@Number nvarchar(4000))SELECT top 1 Numb' 需要参数 '@Number'，但未提供该参数。
2018-04-26 21:00:33,715 [147] ERROR LeaRun.DataAccess.DbHelper - “U_Number”附近有语法错误。
2018-04-26 21:01:01,524 [147] ERROR LeaRun.DataAccess.DbHelper - “U_Number”附近有语法错误。
