2018-05-07 15:57:13,625 [35] ERROR LeaRun.DataAccess.DbHelper - 不存在从对象类型 System.Data.SqlClient.SqlParameter 到已知的托管提供程序本机类型的映射。
2018-05-07 15:57:39,712 [30] ERROR LeaRun.DataAccess.DbHelper - 不存在从对象类型 System.Data.SqlClient.SqlParameter 到已知的托管提供程序本机类型的映射。
2018-05-07 15:58:32,063 [32] ERROR LeaRun.DataAccess.DbHelper - 不存在从对象类型 System.Data.SqlClient.SqlParameter 到已知的托管提供程序本机类型的映射。
2018-05-07 16:02:21,667 [25] ERROR LeaRun.DataAccess.DbHelper - 不存在从对象类型 System.Data.SqlClient.SqlParameter 到已知的托管提供程序本机类型的映射。
2018-05-07 16:02:29,000 [24] ERROR LeaRun.DataAccess.DbHelper - 不存在从对象类型 System.Data.SqlClient.SqlParameter 到已知的托管提供程序本机类型的映射。
2018-05-07 16:12:16,727 [16] ERROR LeaRun.DataAccess.DbHelper - 不存在从对象类型 System.Collections.Generic.List`1[[LeaRun.Entity.Am_BillContent, LeaRun.Entity, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] 到已知的托管提供程序本机类型的映射。
2018-05-07 16:12:37,363 [18] ERROR LeaRun.DataAccess.DbHelper - 不存在从对象类型 System.Collections.Generic.List`1[[LeaRun.Entity.Am_BillContent, LeaRun.Entity, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] 到已知的托管提供程序本机类型的映射。
2018-05-07 16:15:18,974 [20] ERROR LeaRun.DataAccess.DbHelper - 不存在从对象类型 LeaRun.Entity.Am_BillContent 到已知的托管提供程序本机类型的映射。
2018-05-07 16:25:42,050 [18] ERROR LeaRun.DataAccess.DbHelper - 不存在从对象类型 LeaRun.Entity.Am_BillContent 到已知的托管提供程序本机类型的映射。
2018-05-07 16:26:50,852 [25] ERROR LeaRun.DataAccess.DbHelper - 不能将值 NULL 插入列 'ChargeItem_ChargeType'，表 'AmmeterDB.dbo.Am_BillContent'；列不允许有 Null 值。INSERT 失败。
语句已终止。
2018-05-07 16:26:53,042 [25] ERROR LeaRun.DataAccess.DbHelper - 不能将值 NULL 插入列 'ChargeItem_ChargeType'，表 'AmmeterDB.dbo.Am_BillContent'；列不允许有 Null 值。INSERT 失败。
语句已终止。
2018-05-07 16:26:54,988 [25] ERROR LeaRun.DataAccess.DbHelper - 不能将值 NULL 插入列 'ChargeItem_ChargeType'，表 'AmmeterDB.dbo.Am_BillContent'；列不允许有 Null 值。INSERT 失败。
语句已终止。
2018-05-07 16:37:54,991 [14] ERROR LeaRun.DataAccess.DbHelper - 不能将值 NULL 插入列 'ChargeItem_ChargeType'，表 'AmmeterDB.dbo.Am_BillContent'；列不允许有 Null 值。INSERT 失败。
语句已终止。
2018-05-07 16:37:55,031 [14] ERROR LeaRun.DataAccess.DbHelper - 不能将值 NULL 插入列 'ChargeItem_ChargeType'，表 'AmmeterDB.dbo.Am_BillContent'；列不允许有 Null 值。INSERT 失败。
语句已终止。
2018-05-07 16:38:42,596 [14] ERROR LeaRun.DataAccess.DbHelper - 不能将值 NULL 插入列 'ChargeItem_ChargeType'，表 'AmmeterDB.dbo.Am_BillContent'；列不允许有 Null 值。INSERT 失败。
语句已终止。
2018-05-07 16:38:44,367 [14] ERROR LeaRun.DataAccess.DbHelper - 不能将值 NULL 插入列 'ChargeItem_ChargeType'，表 'AmmeterDB.dbo.Am_BillContent'；列不允许有 Null 值。INSERT 失败。
语句已终止。
2018-05-07 16:39:10,717 [14] ERROR LeaRun.DataAccess.DbHelper - 不能将值 NULL 插入列 'ChargeItem_ChargeType'，表 'AmmeterDB.dbo.Am_BillContent'；列不允许有 Null 值。INSERT 失败。
语句已终止。
2018-05-07 16:39:14,867 [14] ERROR LeaRun.DataAccess.DbHelper - 不能将值 NULL 插入列 'ChargeItem_ChargeType'，表 'AmmeterDB.dbo.Am_BillContent'；列不允许有 Null 值。INSERT 失败。
语句已终止。
