2018-04-27 14:49:39,744 [20] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@U_Number nvarchar(36),@Number nvarchar(4000))SELECT top 1 Numb' 需要参数 '@Number'，但未提供该参数。
2018-04-27 14:51:31,418 [13] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@U_Number nvarchar(36),@Number nvarchar(4000))SELECT top 1 Numb' 需要参数 '@Number'，但未提供该参数。
2018-04-27 16:28:46,808 [87] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@AmmeterNumber nvarchar(4000),@U_Number nvarchar(36),@STATUS nv' 需要参数 '@AmmeterNumber'，但未提供该参数。
2018-04-27 16:31:09,033 [22] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@AmmeterNumber nvarchar(4000),@U_Number nvarchar(36),@STATUS nv' 需要参数 '@AmmeterNumber'，但未提供该参数。
2018-04-27 16:31:40,944 [13] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@AmmeterNumber nvarchar(4000),@U_Number nvarchar(36),@STATUS nv' 需要参数 '@AmmeterNumber'，但未提供该参数。
2018-04-27 16:32:49,952 [88] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@AmmeterNumber nvarchar(4000),@U_Number nvarchar(36),@STATUS nv' 需要参数 '@AmmeterNumber'，但未提供该参数。
2018-04-27 17:43:46,146 [14] ERROR LeaRun.DataAccess.DbHelper - 列名 'CreatTime' 无效。
