2018-05-08 10:51:57,006 [21] ERROR LeaRun.DataAccess.DbHelper - 不能将值 NULL 插入列 'Number'，表 'AmmeterDB.dbo.Am_RepairAnswer'；列不允许有 Null 值。INSERT 失败。
语句已终止。
2018-05-08 10:51:57,035 [21] ERROR LeaRun.DataAccess.DbHelper - 无法更新标识列 'RepairCode'。
2018-05-08 10:54:28,632 [37] ERROR LeaRun.DataAccess.DbHelper - 不能将值 NULL 插入列 'Number'，表 'AmmeterDB.dbo.Am_RepairAnswer'；列不允许有 Null 值。INSERT 失败。
语句已终止。
2018-05-08 10:54:45,629 [37] ERROR LeaRun.DataAccess.DbHelper - 无法更新标识列 'RepairCode'。
2018-05-08 10:56:47,532 [37] ERROR LeaRun.DataAccess.DbHelper - 不能将值 NULL 插入列 'Number'，表 'AmmeterDB.dbo.Am_RepairAnswer'；列不允许有 Null 值。INSERT 失败。
语句已终止。
2018-05-08 10:56:47,552 [37] ERROR LeaRun.DataAccess.DbHelper - 无法更新标识列 'RepairCode'。
2018-05-08 10:58:33,614 [11] ERROR LeaRun.DataAccess.DbHelper - 无法更新标识列 'RepairCode'。
2018-05-08 10:59:19,346 [11] ERROR LeaRun.DataAccess.DbHelper - 无法更新标识列 'RepairCode'。
2018-05-08 16:58:55,469 [252] ERROR LeaRun.DataAccess.DbHelper - 列名 'Ammeter_Number' 无效。
2018-05-08 17:00:09,663 [244] ERROR LeaRun.DataAccess.DbHelper - 列名 'Ammeter_Number' 无效。
2018-05-08 17:01:26,126 [242] ERROR LeaRun.DataAccess.DbHelper - 列名 'UY_Number' 无效。
2018-05-08 17:02:28,885 [242] ERROR LeaRun.DataAccess.DbHelper - 另一个 SqlParameterCollection 中已包含 SqlParameter。
2018-05-08 17:06:47,274 [238] ERROR LeaRun.DataAccess.DbHelper - 列名 'UY_Number' 无效。
2018-05-08 17:07:05,128 [241] ERROR LeaRun.DataAccess.DbHelper - 列名 'UY_Number' 无效。
