2018-05-02 10:23:13,465 [26] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@F_U_Number nvarchar(36),@StarTime nvarchar(4000),@EndTime nvar' 需要参数 '@StarTime'，但未提供该参数。
2018-05-02 10:34:55,601 [16] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@F_U_Number nvarchar(36),@StarTime nvarchar(4000),@EndTime nvar' 需要参数 '@StarTime'，但未提供该参数。
2018-05-02 10:35:05,850 [16] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@F_U_Number nvarchar(36),@StarTime nvarchar(4000),@EndTime nvar' 需要参数 '@StarTime'，但未提供该参数。
2018-05-02 10:35:53,844 [42] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@F_U_Number nvarchar(36),@StarTime nvarchar(4000),@EndTime nvar' 需要参数 '@StarTime'，但未提供该参数。
2018-05-02 14:22:25,152 [57] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@T_U_Number nvarchar(36),@Status nvarchar(1),@Number nvarchar(4' 需要参数 '@Number'，但未提供该参数。
2018-05-02 14:29:39,769 [76] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@T_U_Number"。
2018-05-02 14:29:42,197 [75] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@T_U_Number"。
2018-05-02 14:29:49,463 [76] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@T_U_Number"。
2018-05-02 14:29:53,578 [77] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@T_U_Number"。
2018-05-02 14:30:02,115 [77] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@T_U_Number"。
2018-05-02 14:30:26,306 [77] ERROR LeaRun.DataAccess.DbHelper - 另一个 SqlParameterCollection 中已包含 SqlParameter。
2018-05-02 14:58:04,732 [15] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@Number"。
2018-05-02 14:58:35,119 [19] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@Number"。
2018-05-02 14:58:51,175 [13] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@Number"。
2018-05-02 14:59:06,035 [48] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@Number"。
2018-05-02 14:59:06,142 [15] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@Number"。
2018-05-02 14:59:23,963 [46] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@Number"。
2018-05-02 14:59:39,577 [46] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@Number"。
2018-05-02 17:06:19,689 [62] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@U_Number nvarchar(36),@Number nvarchar(4000))SELECT top 1 Numb' 需要参数 '@Number'，但未提供该参数。
2018-05-02 19:11:17,153 [97] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@U_Number nvarchar(36),@Number nvarchar(4000))SELECT top 1 Numb' 需要参数 '@Number'，但未提供该参数。
2018-05-02 19:20:59,980 [99] ERROR LeaRun.DataAccess.DbHelper - 将截断字符串或二进制数据。
语句已终止。
2018-05-02 19:21:00,092 [99] ERROR LeaRun.DataAccess.DbHelper - 将截断字符串或二进制数据。
语句已终止。
