2018-05-11 15:06:03,949 [282] ERROR LeaRun.DataAccess.DbHelper - 列名 'Am_Number' 无效。
2018-05-11 15:06:23,984 [292] ERROR LeaRun.DataAccess.DbHelper - 列名 'Am_Number' 无效。
2018-05-11 15:07:21,844 [292] ERROR LeaRun.DataAccess.DbHelper - 另一个 SqlParameterCollection 中已包含 SqlParameter。
2018-05-11 18:40:09,336 [229] ERROR LeaRun.DataAccess.DbHelper - 列名 'UY_Number' 无效。
2018-05-11 18:58:57,158 [219] ERROR LeaRun.DataAccess.DbHelper - 违反了 PRIMARY KEY 约束“PK_Am_Ammeteion_Number”。不能在对象“dbo.Am_AmmeterPermission”中插入重复键。重复键值为 (a3961200-7588-4473-8ac4-14e95ca300b7)。
语句已终止。
2018-05-11 18:59:14,420 [219] ERROR LeaRun.DataAccess.DbHelper - 违反了 PRIMARY KEY 约束“PK_Am_Ammeteion_Number”。不能在对象“dbo.Am_AmmeterPermission”中插入重复键。重复键值为 (a3961200-7588-4473-8ac4-14e95ca300b7)。
语句已终止。
2018-05-11 18:59:54,432 [210] ERROR LeaRun.DataAccess.DbHelper - 违反了 PRIMARY KEY 约束“PK_Am_Ammeteion_Number”。不能在对象“dbo.Am_AmmeterPermission”中插入重复键。重复键值为 (a3961200-7588-4473-8ac4-14e95ca300b7)。
语句已终止。
2018-05-11 19:01:47,528 [210] ERROR LeaRun.DataAccess.DbHelper - 违反了 PRIMARY KEY 约束“PK_Am_Ammeteion_Number”。不能在对象“dbo.Am_AmmeterPermission”中插入重复键。重复键值为 (a3961200-7588-4473-8ac4-14e95ca300b7)。
语句已终止。
2018-05-11 19:01:50,205 [210] ERROR LeaRun.DataAccess.DbHelper - 违反了 PRIMARY KEY 约束“PK_Am_Ammeteion_Number”。不能在对象“dbo.Am_AmmeterPermission”中插入重复键。重复键值为 (a3961200-7588-4473-8ac4-14e95ca300b7)。
语句已终止。
2018-05-11 19:03:21,440 [207] ERROR LeaRun.DataAccess.DbHelper - 违反了 PRIMARY KEY 约束“PK_Am_Ammeteion_Number”。不能在对象“dbo.Am_AmmeterPermission”中插入重复键。重复键值为 (a3961200-7588-4473-8ac4-14e95ca300b7)。
语句已终止。
2018-05-11 19:07:26,661 [209] ERROR LeaRun.DataAccess.DbHelper - 违反了 PRIMARY KEY 约束“PK_Am_Ammeteion_Number”。不能在对象“dbo.Am_AmmeterPermission”中插入重复键。重复键值为 (a3961200-7588-4473-8ac4-14e95ca300b7)。
语句已终止。
