2018-05-10 11:25:40,005 [97] ERROR LeaRun.DataAccess.DbHelper - 关键字 'and' 附近有语法错误。
2018-05-10 11:25:56,941 [97] ERROR LeaRun.DataAccess.DbHelper - 另一个 SqlParameterCollection 中已包含 SqlParameter。
2018-05-10 14:28:36,342 [125] ERROR LeaRun.DataAccess.DbHelper - 变量名 '@SendTime' 已声明。变量名在查询批次或存储过程内部必须唯一。
2018-05-10 14:29:31,016 [125] ERROR LeaRun.DataAccess.DbHelper - 另一个 SqlParameterCollection 中已包含 SqlParameter。
