2018-06-06 15:05:44,578 [10] ERROR LeaRun.DataAccess.DbHelper - 
2018-06-06 15:05:51,887 [14] ERROR LeaRun.DataAccess.DbHelper - 
2018-06-06 15:06:01,321 [11] ERROR LeaRun.DataAccess.DbHelper - 连接超时时间已到。在尝试使用预登录握手确认时超过了此超时时间。这可能是因为预登录握手失败或服务器未能及时响应。  尝试连接到此服务器时花费的持续时间是 - [Pre-Login] initialization=4223；handshake=16917；
2018-06-06 15:07:05,220 [6] ERROR LeaRun.DataAccess.DbHelper - 
2018-06-06 15:07:05,231 [13] ERROR LeaRun.DataAccess.DbHelper - 
2018-06-06 15:08:09,927 [13] ERROR LeaRun.DataAccess.DbHelper - 
2018-06-06 15:13:09,637 [16] ERROR LeaRun.DataAccess.DbHelper - 
2018-06-06 15:15:52,000 [15] ERROR LeaRun.DataAccess.DbHelper - 
2018-06-06 15:25:22,053 [27] ERROR LeaRun.DataAccess.DbHelper - 
2018-06-06 15:25:23,687 [27] ERROR LeaRun.DataAccess.DbHelper - 
2018-06-06 15:27:05,112 [27] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@Number"。
2018-06-06 15:27:05,151 [27] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@Number nvarchar(4000))SELECT top 1 Number,AM_Code,AmmeterType_' 需要参数 '@Number'，但未提供该参数。
2018-06-06 15:27:12,391 [34] ERROR LeaRun.DataAccess.DbHelper - 
2018-06-06 15:27:13,049 [34] ERROR LeaRun.DataAccess.DbHelper - 
2018-06-06 15:29:54,811 [34] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@Number"。
2018-06-06 15:29:54,837 [34] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@Number nvarchar(4000))SELECT top 1 Number,AM_Code,AmmeterType_' 需要参数 '@Number'，但未提供该参数。
2018-06-06 17:03:08,792 [154] ERROR LeaRun.DataAccess.DbHelper - 
2018-06-06 17:03:09,175 [160] ERROR LeaRun.DataAccess.DbHelper - 
2018-06-06 17:03:28,994 [160] ERROR LeaRun.DataAccess.DbHelper - 
2018-06-06 17:04:33,480 [161] ERROR LeaRun.DataAccess.DbHelper - 
2018-06-06 17:05:21,182 [160] ERROR LeaRun.DataAccess.DbHelper - 
2018-06-06 17:06:53,837 [154] ERROR LeaRun.DataAccess.DbHelper - 
2018-06-06 17:18:36,430 [7] ERROR LeaRun.DataAccess.DbHelper - 
2018-06-06 17:18:37,350 [7] ERROR LeaRun.DataAccess.DbHelper - 
2018-06-06 17:18:56,696 [6] ERROR LeaRun.DataAccess.DbHelper - 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接)
2018-06-06 17:19:27,739 [12] ERROR LeaRun.DataAccess.DbHelper - 
2018-06-06 17:19:28,542 [12] ERROR LeaRun.DataAccess.DbHelper - 
2018-06-06 18:50:16,248 [82] ERROR LeaRun.DataAccess.DbHelper - 
2018-06-06 18:50:17,074 [82] ERROR LeaRun.DataAccess.DbHelper - 
2018-06-06 18:52:06,172 [6] ERROR LeaRun.DataAccess.DbHelper - 
2018-06-06 18:52:06,180 [6] ERROR LeaRun.DataAccess.DbHelper - 
2018-06-06 18:52:48,213 [7] ERROR LeaRun.DataAccess.DbHelper - 
2018-06-06 18:52:48,213 [7] ERROR LeaRun.DataAccess.DbHelper - 
2018-06-06 18:53:02,920 [13] ERROR LeaRun.DataAccess.DbHelper - 
2018-06-06 18:53:02,920 [13] ERROR LeaRun.DataAccess.DbHelper - 
2018-06-06 18:55:05,333 [17] ERROR LeaRun.DataAccess.DbHelper - 
2018-06-06 18:55:05,342 [17] ERROR LeaRun.DataAccess.DbHelper - 
2018-06-06 20:02:11,251 [108] ERROR LeaRun.DataAccess.DbHelper - 
2018-06-06 20:02:11,974 [108] ERROR LeaRun.DataAccess.DbHelper - 
2018-06-06 20:12:16,534 [101] ERROR LeaRun.DataAccess.DbHelper - 
2018-06-06 20:12:17,294 [101] ERROR LeaRun.DataAccess.DbHelper - 
2018-06-06 20:12:35,994 [101] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@Status int,@StatusStr nvarchar(2),@OverTime datetime,@TaskMark' 需要参数 '@Number'，但未提供该参数。   在 System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   在 System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   在 System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   在 System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   在 System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   在 System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   在 System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   在 System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   在 System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   在 LeaRun.DataAccess.DbHelper.ExecuteNonQuery(CommandType cmdType, String cmdText, DbParameter[] parameters) 位置 F:\项目\程序\zst\LeaRun.DataAccess\DataAccess\DbProvider\DbHelper.cs:行号 63
2018-06-06 20:13:07,891 [95] ERROR LeaRun.DataAccess.DbHelper - 
2018-06-06 20:13:08,886 [95] ERROR LeaRun.DataAccess.DbHelper - 
2018-06-06 20:13:41,618 [95] ERROR LeaRun.DataAccess.DbHelper - 
2018-06-06 20:13:42,485 [95] ERROR LeaRun.DataAccess.DbHelper - 
2018-06-06 20:13:47,494 [96] ERROR LeaRun.DataAccess.DbHelper - 
2018-06-06 20:13:48,395 [96] ERROR LeaRun.DataAccess.DbHelper - 
2018-06-06 20:14:34,172 [96] ERROR LeaRun.DataAccess.DbHelper - 
2018-06-06 20:14:35,014 [96] ERROR LeaRun.DataAccess.DbHelper - 
2018-06-06 20:19:37,185 [95] ERROR LeaRun.DataAccess.DbHelper - 
2018-06-06 20:19:38,282 [95] ERROR LeaRun.DataAccess.DbHelper - 
